services:
  mysql:
    image: mysql:8.0.12
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app
    tty: true
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test1234!
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=test1234!
      - MYSQL_DATABASE=my_db
    ports:
      - '3306:3306'
    cap_add:
      - SYS_NICE # CAP_SYS_NICE

  psql:
    image: postgres:15.1-bullseye
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app
    tty: true
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test1234!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_db
    ports:
      - '5433:5432'

  adminer:
    tty: true
    restart: unless-stopped
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080
    depends_on:
      psql:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - app

volumes:
  mysql:
    driver: local
  psql:
    driver: local

networks:
  app:
    driver: bridge